import { useRouter } from 'next/router'
import type { NextPage } from "next";
import Head from "next/head";
import { useQuery } from "react-query";


const Poem: NextPage = () => {
  const router = useRouter()
  const { id } = router.query

  const fetchPoem = () =>
  fetch(`http://127.0.0.1:8000/api/v1/poems/${id}`).then((response) =>
    response.json()
  );
  const { isLoading, isError, data, error } = useQuery("poem", fetchPoem);

  if (isLoading) {
    return <span>Loading...</span>;
  }

  if (isError) {
    return <span>Error: {error}</span>;
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-green-500">hi</h1>
  

          <li className="p-1">{data.title}</li>
    
    </div>
  );
}

export default Poem