import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import { useQuery } from "react-query";

const fetchAllPoems = () =>
  fetch("http://127.0.0.1:8000/api/v1/poems/").then((response) =>
    response.json()
  );

const Poems: NextPage = () => {
  const { isLoading, isError, data, error } = useQuery("poems", fetchAllPoems);

  if (isLoading) {
    return <span>Loading...</span>;
  }

  if (isError) {
    return <span>Error: {error}</span>;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-green-500">hi</h1>
      {data.map((poem: any) => (
        <ul key={poem._id}>
          <Link href={`/poems/${encodeURIComponent(poem._id)}`}>
            <a>{poem.title}</a>
          </Link>
          <li className="p-1">{poem.poet}</li>
        </ul>
      ))}
      <Link href={`/poems/add`}>
            <a>New</a>
          </Link>
    </div>
  );
};

export default Poems;
