import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import { useQuery } from "react-query";
import {
  Box,
  Heading,
  Text,
  Container,
  Divider,
  useColorModeValue,
} from "@chakra-ui/react";

const fetchAllPoems = () =>
  fetch("http://127.0.0.1:8000/api/v1/poems/").then((response) =>
    response.json()
  );

const Poems: NextPage = () => {
  const { isLoading, isError, data, error } = useQuery("poems", fetchAllPoems);

  if (isLoading) {
    return <span>Loading...</span>;
  }

  if (isError) {
    return <span>Error: {error}</span>;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        maxW="container.md"
        bg={useColorModeValue("white", "gray.900")}
        boxShadow={"2xl"}
        rounded={"lg"}
      >
        {data.map((poem: any) => (
          <Box key={poem._id} textAlign="left" py={2} px={6}>
            <Heading as="h3" size="lg" mt={2} mb={2}>
              {poem.title}
            </Heading>
            <Text mb={5} color={"gray.500"}>
              {poem.poet}
            </Text>
            <Divider />
          </Box>
        ))}
      </Container>
      <Link href={`/poems/add`}>
        <a>New</a>
      </Link>
    </div>
  );
};

export default Poems;
