import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Hero from "../components/hero"


const Home: NextPage = () => {

   return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Link href="/poems">
        <a>Poems</a>
      </Link>
    </div>
  );
};

export default Home;
