import type { NextPage } from "next";
import Head from "next/head";
import { useQuery } from 'react-query'

const fetcher = () => fetch('http://127.0.0.1:8000/').then(response => response.json())



const Home: NextPage = () => {


  const { isLoading, isError, data, error } = useQuery("users", fetcher);

  if (isLoading) {
    return <span>Loading...</span>;
  }

  if (isError) {
    return <span>Error: {error.message}</span>;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-green-500">hi</h1>
      {data.map((user: any) => (
         <li key={user.name}>{user._id}</li>
       ))}
    </div>
  );
};

export default Home;
